name: Update Operators Cache

on:
  workflow_dispatch:
    inputs:
      mainnet-blob-id:
        description: 'Mainnet blob ID'
        required: true
        type: string
      testnet-blob-id:
        description: 'Testnet blob ID'
        required: true
        type: string

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run cache inference
        run: |
          npx ts-node scripts/cache-inference/cache-inference.ts ${{ github.event.inputs.mainnet-blob-id }} ${{ github.event.inputs.testnet-blob-id }} > docs/book/assets/new-operators.json
          mv docs/book/assets/new-operators.json docs/book/assets/operators.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update operators.json with new cache measurements"
          title: "Update operators.json with new cache measurements"
          body: |
            This PR updates the operators.json file with new cache measurements.

            Mainnet blob ID: ${{ github.event.inputs.mainnet-blob-id }}
            Testnet blob ID: ${{ github.event.inputs.testnet-blob-id }}
          branch: "test/update-operators-cache"
          base: "main"
